### ISSUE TITLE
What is required to support ARM Macs? (Given we have the example libs for python)

### ISSUE THREAD

**Issue by juliangamble** [tensorflow/java-models#26]
There is a page here showing how to setup Tensorflow on Python for M1 ARM Macs:
https://developer.apple.com/metal/tensorflow-plugin/

It seems we could adapt this example for the M1 ARM Macs. 

My question is - what is required?

**Comment by Craigacp** [comment]
We're working on simplifying the build process so we can pull in the TF binaries from the Python whls rather than building it from source. Once that's done it'll be easier for us to build the TF-Java binding for macOS ARM64 locally and upload it, then there will be support for that platform. At the moment we build TF-Java (both the TF native library and the TF JavaCPP binding) on Github Actions, there aren't any macOS ARM64 Github hosted runners and we have no build resources from Google (Google have been outsourcing builds for non-Linux platforms to other people anyway, Intel build Windows, AWS build Linux ARM64, Apple build macOS).

Once that's done we'll still need to figure out how to enable the pluggable device support as we looked at it last year and it was troublesome - https://github.com/tensorflow/java/pull/410. Hopefully it'll be simpler with the new build but we don't know yet.

**Comment by juliangamble** [comment]
Thanks, that's really helpful. Is there someone's repo fork I can look at to see a prototype of pulling in the TF binaries from Python? I'm working out if there is a way I can contribute.

**Comment by Craigacp** [comment]
We're discussing how to implement it at the moment, so we don't have code yet. Spent last week checking out the whl file formats to make sure they all look roughly the same.

**Comment by Craigacp** [comment]
Fixed in https://github.com/tensorflow/java/releases/tag/v1.0.0-rc.2
