### ISSUE TITLE
Add missed dependency "org.tensorflow.tools"

### ISSUE THREAD

**Issue by zaleslaw** [tensorflow/java-models#4]
import org.tensorflow.tools.Shape;
import org.tensorflow.tools.ndarray.ByteNdArray;
import org.tensorflow.tools.ndarray.FloatNdArray;
import org.tensorflow.tools.ndarray.index.Indices;

these imports are not found, I'd suggest the simplest solution via addition of missed dependency

**Comment by karllessard** [comment]
Please tell me if [that commit](https://github.com/tensorflow/java-models/commit/d91770c726734942d8585511df170be31e423e6c) also fixed this issue

**Comment by karllessard** [comment]
@zaleslaw , I was able to reproduce that error on my IntelliJ as well (it seems to be a IDEA bug). I have a module A that depends on another module B depending on `tensorflow-core-platform`. Module A then inherit from the following dependencies:

`ModuleA -> ModuleB -> (tensorflow-core-platform) -> (tensorflow-core-api)`

It should have retrieve transitive dependencies from `tensorflow-core-api` though. I found that [old and long thread](https://youtrack.jetbrains.com/issue/IDEA-98425) on IntelliJ forum where someone suggested to enable the following parameter in my workspace:

![image](https://user-images.githubusercontent.com/10109534/82479861-f3908100-9aa0-11ea-9fef-e9ceaabcfaab.png)

I did not went through the whole thread nor tried to understand much what I was doing but it worked out in my case, with this parameter set, I now retrieve dependencies from `tensorflow-core-api` transitively, which includes `tensorflow-tools`, `protobuf`, etc. 

Let me know if that fixes your issue as well. We might want to try to understand better what is going on with IDEA too...

**Comment by zaleslaw** [comment]
Ok, will try to reproduce in the next few days

ср, 20 мая 2020 г., 20:53 Karl Lessard <notifications@github.com>:

**Comment by zaleslaw** [comment]
@karllessard unfortunately, it doesn't help, but agree, that this is a strange behaviour with transitive dependencies (maybe somebody will experiment with that).

Does it wok correctly without IDEA, via MVN only?

**Comment by zaleslaw** [comment]
Currently, I need to add to POM two dependencies to run correctly

    <dependency>
      <groupId>org.tensorflow</groupId>
      <artifactId>tensorflow-tools</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.8.0</version>
    </dependency>

**Comment by karllessard** [comment]
you should need to add these, that's the point, and yes it worked using Maven exclusively in my case, please remove these two dependencies and give a try to `mvn clean install` to see if that works for you as well.

**Comment by karllessard** [comment]
Hey guys, I'm hitting this issue again as well and even with `mvn clean install`, it does not work. Looking at the `pom` deployed in Nexus, it looks like the [latest one](https://oss.sonatype.org/service/local/repositories/snapshots/content/org/tensorflow/tensorflow-core-api/0.1.0-SNAPSHOT/tensorflow-core-api-0.1.0-20200618.101156-199.pom) for `tensorflow-core-api` is almost empty, while it should contain the whole pom like [the previous one](https://oss.sonatype.org/service/local/repositories/snapshots/content/org/tensorflow/tensorflow-core-api/0.1.0-SNAPSHOT/tensorflow-core-api-0.1.0-20200618.100812-198.pom). So that probably explains why transitive dependencies are not uploaded automatically.

@saudet, I know that the last artifacts were deployed from your fork, any idea why the resulting pom would look like this? I'm building new artifacts as I write now so we will see what happens.

**Comment by karllessard** [comment]
Ok I did some progress on this, so from the last build, I can that all poms are delivered correctly by each platform (as we deploy everything for each platform). 

The problem is when all builds are completed and the `tensorflow-core-api` artifacts are redeployed, the `pom.xml` is not redeployed with the jars, so Maven generates a default(empty) one for this deployment. That one causes our transitive dependency issue. 

I'll disable the redeployment step for now so the artifacts can be used again, we should see then how we should reenable it to include the pom as well (BTW what was the reason for that redeployment again, was it only for gradle?)

**Comment by karllessard** [comment]
Finally what I did is to disable the generation of the default pom on redeployment, we will see how it goes after the build currently in progress

**Comment by saudet** [comment]
> The problem is when all builds are completed and the `tensorflow-core-api` artifacts are redeployed, the `pom.xml` is not redeployed with the jars, so Maven generates a default(empty) one for this deployment. That one causes our transitive dependency issue.

Let me fix that...

> I'll disable the redeployment step for now so the artifacts can be used again, we should see then how we should reenable it to include the pom as well (BTW what was the reason for that redeployment again, was it only for gradle?)

Gradle, sbt, etc and Sonatype OSSRH: https://github.com/tensorflow/java/pull/37#issuecomment-610126078

**Comment by karllessard** [comment]
@saudet I've [disabled the generation](https://github.com/tensorflow/java/blob/687a6d9f160a7a05cf8adcc776e75e78932237b9/tensorflow-core/pom.xml#L113) of the default pom on redeploy, meaning that it will keep the original pom instead (with the old timestamp though). If you don't think that would work for Gradle, then we probably just need to redeploy the pom as well. 

(Note that the build is almost complete so we will be able to test it in a few minutes)

**Comment by karllessard** [comment]
Ok @saudet , so build is complete and all transitive dependencies are now fetched without any issue, as expected. If you prefer to push a different solution, just push a PR and I'll merge it but I'm curious, what could go wrong with this one?

**Comment by saudet** [comment]
The pom.xml file is missing, so, yeah that won't work.

**Comment by karllessard** [comment]
> The pom.xml file is missing, so, yeah that won't work.

It does work, for Maven at least. I don't know for Gradle. I've retriggered my Jenkins job that was failing and it passed through, Maven picks the last `pom.xml` deployed when we build the platform jobs, as listed in the `maven-metadata.xml`.

Anyway, I don't mind trying something else if you feel more confident.
